version: '3.8'

services:
  chess-importer:
    build: .
    container_name: chess_importer
    restart: unless-stopped
    volumes:
      - .:/app  # Mount current directory
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
      - PATH="/opt/venv/bin:$PATH"  # Ensure venv is used