version: '3.8'

services:
  chess-importer:
    build: .
    container_name: chess_importer
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml  # if you need to edit config
      - ./data:/app/data                # persistent data
      - ./logs:/app/logs                # persistent logs
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true