version: '3.8'

services:
  chess-importer:
    build: .
    container_name: chess_importer
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
    volumes:
      - chess-data:/data
    user: "${UID:-1000}:${GID:-1000}"  # Match host user permissions


volumes:
  chess-data: