version: '3.8'

services:
  chess-importer:
    build: .  # Simple build without target
    container_name: chess_importer
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs