version: '3.8'

services:
  chess-importer:
    build:
      context: .
      # This forces Docker to rebuild every time
      target: chess_importer
    container_name: chess_importer
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs